version: '2'

services:
  db:
    image: 'postgres:9.6'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    command:
      - postgres
      - -c
      - 'shared_buffers=500MB'
      - -c
      - 'max_connections=500'
